name: Workflow level variables

on: workflow_dispatch

env:
    CLOUD: AWS Cloud

#Picks from workflow level variable    
jobs:
    print-cloud:
        runs-on: ubuntu-latest
        steps:
            - name: Print cloud variable
              run: echo "I am running on $CLOUD"
#Job level variable overrides workflow level variable
    print-cloud-again:
        runs-on: ubuntu-latest
        env:
            CLOUD: Azure Cloud
        steps:
            - name: Print cloud variable again
              run: echo "I am running on $CLOUD"
#Step level variable overrides job and workflow level variable
    print-cloud-step-level:
        runs-on: ubuntu-latest
        steps:
            - name: Print cloud variable again
              env:
                CLOUD: Google Cloud
              run: echo "I am running on $CLOUD"
#config variables are defined at the repository level and can be used across all workflows in the repository. They are accessed using the vars context and take precedence over workflow, job, and step level variables.
    print-repo-level-variable:
        runs-on: ubuntu-latest
        steps:
            - name: Print project variable 
              env:
                CLOUD: Google Cloud
              run: echo "I am running a project named ${{ vars.PROJECT_ID }}"