name: Secret

on: workflow_dispatch

jobs:
  print-cloud:
    runs-on: ubuntu-latest

    steps:
      - name: The repo name
        run: echo "I am on ${{ github.repository }}"
      - name: Print workflow
        run: echo "I am running workflow ${{ github.workflow }}"
      - name: Triggered by
        run: echo "I am running as ${{ github.actor }}"
      - name: Secret variable 1
        run: echo "this access key is configured ${{ secrets.AWS_ACCESS_KEY }}" 
      - name: Secret variable 1
        run: echo "this access key is configured ${{ secrets.AWS_SECRET_KEY }}" 

