name: job dependencies

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment for deployment"
        default: dev
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code from github repo
        run: echo "Code cloned from the github repo"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: echo "Docker image build succesfully"
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Running tests on Docker file
        run: echo "Docker Images tested"
        
  deploy-to-dev:
    needs: [build, test]
    if: ${{ inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Dev environment
        run: echo "Deployed to Dev Succesfully"

  deploy-to-uat:
    needs: [build, test]
    if: ${{ inputs.environment == 'uat' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Dev environment
        run: echo "Deployed to uat Succesfully"    
