name: Code Quality with flake and bandit

on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Dependencies and Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install flake8 bandit

      - name: Run Flake8
        run: flake8 app.py

      - name: Run Bandit
        run: bandit app.py
