name: Deploy to EC2 instance

on:
  push:
    branches:
      - main
      - dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: setup ssh key
        run: |
          echo "${{ secrets.SSHKEY }}" > key.pem
          chmod 400 key.pem

      - name: copy SCP files to EC2
        run: 
          sudo scp -o StrictHostKeyChecking=no -i key.pem -r index.html ${{ secrets.USER }}@${{ secrets.IP }}:/var/www/html/
