name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  call-build:
    uses: ./.github/workflows/dockerpush.yml
    secrets: inherit

  call-scan:
    needs: call-build
    uses: ./.github/workflows/imagescan.yml
    secrets: inherit
